### ISSUE TITLE
store path 'xxx-.platformio' starts with illegal character '.'

### ISSUE THREAD

**Issue by DavHau** [risicle/nix-heuristic-gc#6]
2024-06-28 17:51:34,941:INFO:nix_heuristic_gc.graph: topologically sorting paths
Traceback (most recent call last):
  File "/nix/store/0dsx2am4f4a4l8dmljvh0spfvp7p2s5l-python3.10-nix-heuristic-gc-0.5.0/bin/.nix-heuristic-gc-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0dsx2am4f4a4l8dmljvh0spfvp7p2s5l-python3.10-nix-heuristic-gc-0.5.0/lib/python3.10/site-packages/nix_heuristic_gc/__main__.py", line 184, in main
    nix_heuristic_gc(**parsed)
  File "/nix/store/0dsx2am4f4a4l8dmljvh0spfvp7p2s5l-python3.10-nix-heuristic-gc-0.5.0/lib/python3.10/site-packages/nix_heuristic_gc/__init__.py", line 49, in nix_heuristic_gc
    garbage_graph = GarbageGraph(
  File "/nix/store/0dsx2am4f4a4l8dmljvh0spfvp7p2s5l-python3.10-nix-heuristic-gc-0.5.0/lib/python3.10/site-packages/nix_heuristic_gc/graph.py", line 172, in __init__
    garbage_store_paths_sorted = self.store.topo_sort_paths(garbage_store_path_set)
RuntimeError: error: store path 'kxal8b03mxbiqsbv191i488956ydg3cw-.platformio' starts with illegal character '.'

**Comment by risicle** [comment]
Hmmm https://github.com/NixOS/nix/issues/9624

Guess I should update the default version of nixpkgs in the flake anyway.

**Comment by risicle** [comment]
Try with 0.5.1 now.

Assuming you use any of the default dependencies for building.

**Comment by DavHau** [comment]
Thanks for the fix. Seems like now I'm getting a different error: https://github.com/risicle/nix-heuristic-gc/issues/7
